### ISSUE TITLE
Program crashes if email does not exist in json file

### ISSUE THREAD

**Issue by Matthew-Beliveau** [Matthew-Beliveau/SecureDrop#4]
https://github.com/Matthew-Beliveau/SecureDrop/blob/4e0522b6d75d81036f84b2861fe71f8c93135b83/sd_shell.py#L128

**Comment by yorgokennos** [comment]
Fixed and Tested! See pull request below
#8

**Comment by yorgokennos** [comment]
closed the wrong issue, re-opening

**Comment by yorgokennos** [comment]
#8 added condition in login_helper() to handle the input of an unregistered user
